config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'events/new'

	root 'static_page#home'
	get '/create_event', to: 'events#new'
	post '/create_event', to: 'events#create'
	get '/manage_event', to: 'events#index'
	resources :events
	resources :attendees, only: [:create]
	

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :event
	validates :event_id, presence: true
	before_save {email.downcase!}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false, scope: :event_id }
	

end

app/models/event.rb
class Event < ApplicationRecord
	has_many :attendees, dependent: :destroy
	validates :name, presence: true, length: { maximum: 50 }
	validates :location, presence: true, length: { maximum: 100 }
	validates :time, presence: true
	validates :date, presence: true
	validates :location, uniqueness: { scope: [:time, :date] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
	def create
		@attendee = current_event.attendees.build(attendee_params)
		if @attendee.save
			flash[:success] = "A new attendee was added"
		else
			flash[:danger] = "Could not add attendee because of format/duplicate/blank" 
		end
		redirect_to current_event
	end

	private 
		
		def attendee_params
			params.require(:attendee).permit(:email)
		end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def new
    @event = Event.new
  end

  def show
		if managing?
			stop_manage
		end
		@event = Event.find(params[:id])
		manage @event
		@attendees = @event.attendees
		@attendee = @event.attendees.build
		
  end

  def create
    @event = Event.new(event_params)
    if @event.save
			manage @event
			flash[:success] = "You have successfully created an event!"
      redirect_to @event
    else
      render 'new'
    end
  end
	
	def index
		if managing?
			stop_manage
		end
		@events = Event.all
	end

	def destroy
		if managing?
			stop_manage
		end
		Event.find(params[:id]).destroy
		flash[:success] = "Event Canceled!"
		redirect_to manage_event_path
	end

  private

    def event_params
      params.require(:event).permit(:name, :location, :time, :date)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
	
	def create
	end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title = '')
    base_title = "Event Registration"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
  def manage(event)
    session[:event_id] = event.id
  end

  def current_event
    if session[:event_id]
      @current_event ||= Event.find_by(id: session[:event_id])
    end
  end

  def managing?
    !current_event.nil?
  end

  def stop_manage
    session.delete(:event_id)
    @current_event = nil
  end

end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/attendees/_attendee.html.erb
<% if attendee.valid? %>
	<li>
		
		<span class="email"><%= attendee.email %></span>
		checked in
		<span class="timestamp">
			<% time = attendee.created_at %>
			on
			<%= time_tag(time) %>

		</span>
		

	</li>
<% end %>

app/views/events/_event.html.erb
<li>
	"<%= event.name %>" at <%= event.location %>
	on <%= event.date.strftime("%m/%d/%Y") %>
	at <%= event.time.strftime("%H:%M") %>.
	 | <%= link_to "Cancel Event", event, method: :delete,
																	date: { confirm: "You sure?" } %>
	 | <%= link_to "Add/See Attendees", event, method: :get %>
	
</li>

app/views/events/index.html.erb
<% provide(:title, "Manage Events") %>
<h1>Manage Events</h1>

<ul class="events">
	<% @events.each do |event| %>
		<%= render event %>
	<% end %>
</ul>

app/views/events/new.html.erb
<% provide(:title, 'Create Event') %>
<h1>Create Event</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@event) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location, class: 'form-control'%>

      <%= f.label :date %>
      <%= f.date_field :date, class: 'form-control' %>

      <%= f.label :time %>
      <%= f.time_field :time, class: 'form-control' %>

      <%= f.submit "Create Event", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<%= provide(:title, @event.name) %>
<h2> Your event, "<%= @event.name %>", will take place at <%= @event.location %>
	on <%= @event.date.strftime("%m/%d/%Y") %> at <%= @event.time.strftime("%H:%M") %>.
</h2>
<div class="row">
	<aside class = "col-md-4">
		<section class="attendee_form">
			<%= render 'shared/attendee_form' %>
		</section>
	</aside>
  <div class="col-md-8">
    <% if @event.attendees.any? %>
      <h3>Attendees (<%= @event.attendees.count %>)</h3>
      <ul class="attendees">
        <%= render @attendees %>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Event Registration ", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path%></li>
        <li><%= link_to "Create Event",   create_event_path %></li>
				<li><%= link_to "Manage Events", manage_event_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= render 'layouts/shim' %>
  </head>

  <body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |message_type, message| %>
				<div class="alert alert-<%= message_type %>"><%= message %></div>
			<% end %>
			<%= yield %>
		</div>
  </body>
</html>

app/views/shared/_attendee_form.html.erb
<%= form_for(@attendee) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.email_field :email, placeholder: "Enter your email to check in " %>
  </div>
  <%= f.submit "Check In", class: "btn btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_page/home.html.erb
<%provide(:title, "Home")%>
<div class="center jumbotron">
  <h1>Welcome to the Event Registration App</h1>

  <h2>
		To use this, simply click "Create New Event" and you will be on your way!
  </h2>
  <%= link_to "Create Event", create_event_path, class: "btn btn-lg btn-primary" %>
</div>